availability_zone: melbourne-qh2-uom
#team 9
#COMP90024 ASSIGNMENT 2
volumes:
   - vol_name: server_db
     vol_size: 30
  #  - vol_name: instance_2_vol_2
  #    vol_size: 10

security_groups:
  - name: ssh
    description: "SSH ACCESS"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

instance_name: instance_4
instance_image: 955a0556-1224-4499-a895-87d54d5cbf32
instance_key_name: team9
instance_flavor: uom.mse.2c9g