# Team: team 9
# City: Melbourne Australia
# Class: COMP90024 ASSIGNMENT 2 - Semester 2, 2019
# Member 1: Naiyun Wu - 1008438
# Member 2: Kuldeep Suhag - 919397
# Member 3: Hongtao Ni - 938737
# Member 4: Duoyi Zhang - 956812
# Member 5: Zexian Huang - 1012710

- name: creat service for docker
  shell: |
    sudo docker service create --replicas 4 -p 80:3000 --name webservice -e "DOCKER_HOST=$(hostname -I)" nnyy10/webserverimage