#team 9
#COMP90024 ASSIGNMENT 2
- name: creat service for docker
  shell: |
    sudo docker service create --replicas 4 -p 80:3000 --name webservice -e "DOCKER_HOST=$(hostname -I)" nnyy10/webserverimage