version: "3"
services:
  couch_master:
    image: "couchdb:2.3.0"
    restart: always
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    links:
      - couch_slave1
      - couch_slave2
    volumes:
      - /Users/alwynpan/Workspace/Teaching/couchdb/master/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.20.0.2
    container_name: couch_master
    networks:
      couchdb_nw:
        ipv4_address: 172.20.0.2
  couch_slave1:
    image: "couchdb:2.3.0"
    restart: always
    ports:
      - "15984:5984"
    volumes:
      - /Users/alwynpan/Workspace/Teaching/couchdb/slave1/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.20.0.3
    container_name: couch_slave1
    networks:
      couchdb_nw:
        ipv4_address: 172.20.0.3
  couch_slave2:
    image: "couchdb:2.3.0"
    restart: always
    ports:
      - "25984:5984"
    volumes:
      - /Users/alwynpan/Workspace/Teaching/couchdb/slave2/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.20.0.4
    container_name: couch_slave2
    networks:
      couchdb_nw:
        ipv4_address: 172.20.0.4

networks:
  couchdb_nw:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16