# Team: team 9
# City: Melbourne Australia
# Class: COMP90024 ASSIGNMENT 2 - Semester 2, 2019
# Member 1: Naiyun Wu - 1008438
# Member 2: Kuldeep Suhag - 919397
# Member 3: Hongtao Ni - 938737
# Member 4: Duoyi Zhang - 956812
# Member 5: Zexian Huang - 1012710

- name: determine swarm status
  become: true
  shell: >
        docker info | egrep '^Swarm' | cut -d ' ' -f2 
  register: swarm_status

- name: "join as a manager"
  shell: "sudo docker swarm join --token {{ hostvars['docker-swarm-1']['manager_token']['stdout'] }} {{ hostvars['docker-swarm-1']['ansible_eth0']['ipv4']['address'] }}:2377"
  when: "'active' not in swarm_status.stdout_lines"
  retries: 3
  delay: 20