- name: create a security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: present
  loop: '{{ security_groups }}'

- name: Create a list of security group name
  set_fact:
    sg_name: '{{ sg_name | default([]) + [ item.name] }}'
  loop: '{{ security_groups }}'

- debug:
    msg: "Security groups {{ sg_name }} have been created"

- name: Create security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
  loop: '{{ security_groups }}'